//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logement
{
    using System;
    using System.Collections.Generic;
    
    public partial class logement
    {
        public int IDLOG { get; set; }
        public Nullable<int> IDLOC { get; set; }
        public Nullable<short> IPPARC { get; set; }
        public string ADRESSE { get; set; }
        public int NB_PIECES { get; set; }
        public double LOYER { get; set; }
    }
}
